apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-deployment
  labels:
    app: aggregator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-service
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
        - name: aggregator-service
          image: aggregator-service:latest
          ports:
            - containerPort: 8080